### ISSUE TITLE
腾讯动漫闪退

### ISSUE THREAD

**Issue by Soulize** [hujiayucc/Fuck-AD#8]
可能是腾讯加固的原因，腾讯动漫会闪退
包名 com.qq.ac.android
报错log 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.qq.e.comm.managers.GDTADManager.initWith(android.content.Context, java.lang.String)' on a null object reference
	at com.qq.e.tg.splash.TGSplashPreloader$1.run(Unknown Source:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by hujiayucc** [comment]
1.1.6 已修复，[https://github.com/hujiayucc/Fuck-AD/releases/tag/1.1.6](https://github.com/hujiayucc/Fuck-AD/releases/tag/1.1.6)

**Comment by Soulize** [comment]
老哥太强了，好快的修
